### ISSUE TITLE
Support for the native iOS SDK of Filepicker.io

### ISSUE THREAD

**Issue by antoniostorni** [dbaq/cordova-plugin-filepickerio#1]
It would be great to have support for the native iOS SDK for this plugin.

**Comment by dbaq** [comment]
If multiple persons are interested I will make that happen.

**Comment by esopian** [comment]
:+1:

**Comment by pixxio** [comment]
I am also VERY interessted in support for iOS

**Comment by dbaq** [comment]
I'll look at it soon. Please keep commenting if you are interested. It'll help me prioritize this task.

**Comment by jwbuitenhuis** [comment]
:+1:

**Comment by justinobney** [comment]
+1

**Comment by Eaven** [comment]
+1

**Comment by dbaq** [comment]
Hey guys, thanks for your patience. I finally implemented the latest Filestack iOS picker. It is on the master branch and available right now.

Please make sure you read this section: https://github.com/dbaq/cordova-plugin-filepickerio#difference-between-ios-and-android.

Feel free to open an issue if you discover a problem.

Cheers 🍻
