### ISSUE TITLE
App crashes on opening picker in some cases

### ISSUE THREAD

**Issue by cwohlman** [dbaq/cordova-plugin-filepickerio#10]
When using the picker I occasionally get this error (which crashes the app):

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'accessing _cachedSystemAnimationFence requires the main thread'
```

Problem seems to be caused because of trying to run this code in a background thread: https://github.com/dbaq/cordova-plugin-filepickerio/blob/master/src/ios/FilePickerIO.m#L52

**Comment by cwohlman** [comment]
Nevermind, I see that this has been fixed already.

Is there any plan to push this update?

**Comment by dbaq** [comment]
I just published a new version on npm sorry.

**Comment by cwohlman** [comment]
Thanks!
