### ISSUE TITLE
Xcode fails to attach app to phone

### ISSUE THREAD

**Issue by adamjpeterson** [dbaq/cordova-plugin-filepickerio#12]
I'm receiving the following error when running my cordova app in Xcode after adding the filepicker plugin. The project appears to build and then fails when attaching to a emulator or my own phone, any thoughts? 

dyld: Library not loaded: @rpath/FSPicker.framework/FSPicker
  Reason: image not found

**Comment by macsharp** [comment]
We encountered a similar issue, which can be fixed by adding the necessary frameworks to the Embedded list. See screenshot. Hope this helps!
![screen shot 2017-08-17 at 2 01 40 pm](https://user-images.githubusercontent.com/5316195/29426458-af2444ea-8354-11e7-9fd8-1ade5e6793db.png)

**Comment by dbaq** [comment]
Correct, I updated the readme file to explain this issue: https://github.com/dbaq/cordova-plugin-filepickerio/commit/9ce87d7875149fb8a6dc33199a23b6d848fe63f9
