### ISSUE TITLE
Plugin calls "success" when showing the picker using pick() and does not show the "Add" button

### ISSUE THREAD

**Issue by macsharp** [dbaq/cordova-plugin-filepickerio#13]
First off, thank you for working on this plugin! It's far superior than the official plugin that's many years old. However, I ran into a few issues and I hope you could help. Thank you in advance for your time!

**Issue #1**
When calling either .pick() or .pickMultiple(), the onSuccess callback gets fired immediately as the picker panel is shown on the device. 

**Issue #2**
After selecting file(s), the file stack panel shows "uploading" and the upload process finished correctly. However, there is no button to complete the Pick action (see screenshot). I can select one or multiple files, but no button to confirm the selection.
![img_1758](https://user-images.githubusercontent.com/5316195/29426626-39e0777a-8355-11e7-8b19-c17bca400ba6.PNG)

**Technical details**
iOS 11 beta 5, Xcode 9 beta 5. iPhone SE.

**Xcode logs** (cleared right before initiating .pick() from js):
2017-08-17 13:57:24.163073-0400 TestApp [2943:2271865] filePicker return successfully.
2017-08-17 13:57:24.163165-0400 TestApp [2943:2271865] null
2017-08-17 13:57:24.182708-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.186978-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.187038-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.187070-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.187096-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.187136-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.187234-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.187345-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.187371-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:57:24.187392-0400 TestApp [2943:2272209] [Assert] Cannot be called with asCopy = NO on non-main thread.
2017-08-17 13:58:41.011403-0400 TestApp [2943:2272601] [GatekeeperXPC] Connection to assetsd was interrupted or assetsd died
2017-08-17 13:58:41.011570-0400 TestApp [2943:2271865] CoreData: XPC: sendMessage: failed #0
2017-08-17 13:58:43.966799-0400 TestApp [2943:2271865] [MC] Reading from public effective user settings.
2017-08-17 13:59:25.181552-0400 TestApp [2943:2271865] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction
2017-08-17 13:59:25.182348-0400 TestApp [2943:2271865] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction
2017-08-17 13:59:27.501050-0400 TestApp [2943:2271865] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction
2017-08-17 13:59:27.501114-0400 TestApp [2943:2271865] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction

**Comment by dbaq** [comment]
Hey @macsharp thanks for opening the issue and sorry for the late answer, I was on vacation. Have you found a solution or not yet? I need to check but we are using this plugin in production without those issues.

**Comment by macsharp** [comment]
@dbaq,
Many thanks for getting back to me! I know I'm asking a lot from you, who provide this plugin at no charge. Therefore I am extremely grateful for the plugin and any insight you could share with me.

No, I haven't been able to figure out a solution for this, and I'm still facing the very same issue. If you want, I can record a screen recording if it's potentially helpful. Please do let me know if you have a theory on this.

One possibility with the issue is that when picking a photo from photo stream, chances are that the photo itself may be hosted on iCloud instead of being available on the local device. So I also tested taking a photo with the camera app to ensure the local availability, and the issue remained the same --- no "Select" button or any similar action buttons on the UI that could confirm the file selection.

So, to confirm, the issue has two visible symptoms:
1) No visible "Select" action after picking and successfully uploading a file object;
2) The success callback actually gets called upon firing of the filepicker itself.

Hope you could help me a little here. Thank you again for your hard work!

**Comment by macsharp** [comment]
@dbaq 
Did you get a chance to look at this issue? Any help is greatly appreciated. Thank you very much!

**Comment by dbaq** [comment]
Hey @macsharp, sorry for the delay. I still haven't had the chance to look at it. I tried on one of my friends' iphone with the beta 7 and it is definitely acting weird. I am in between laptops for now, my MBP died, the next one should arrive next week. So there is not much I can do for now.

What you can do is to try to update the FPicker iOS lib:

1- fork this repo
2- update this file and use `pod "FSPicker", "~> 1.1.8"`
https://github.com/dbaq/cordova-plugin-filepickerio/blob/master/scripts/ios/podfile#L6
3- create a quick cordova project, add this plugin (refer to your local directory on your machine) and try to pick a file.
4- let me know :)

Sorry I can't do more for now

**Comment by macsharp** [comment]
@dbaq Just tried your suggestions... no visible difference, unfortunately. The shot taken from the camera still uploads correctly, but after that point, no "Select" action is visible from the toolbar. I'm not sure if the newer version of FSPicker, 1.1.8, is taking effect though. Is there a way for me to verify that I'm using this newer version? I tried looking into the corresponding Framework folders and couldn't find any reference to the version being 1.1.8 or 0.3.7, etc.

Any advice would be greatly appreciated!

**Comment by macsharp** [comment]
@dbaq, any update on this? Sorry to bother you but I've tried following your instructions earlier and it didn't make a difference.

Thank you very much for your help! It's much appreciated. I can pay you for your work if that's helpful.

**Comment by dbaq** [comment]
@macsharp I can reproduce the error on my machine. I am digging to find out the root cause. In the same time, I am also updating the build to iOS 11 + updating the dependencies. I'll keep you posted.

**Comment by dbaq** [comment]
hey @macsharp, please try the latest version (either master or npm). It fixes the bug on my side. It was due to a race condition when calling successively `setKey`, `setName` and `pick*`.

Let me know if that work for you.
>Thank you very much for your help! It's much appreciated. I can pay you for your work if that's helpful.

You know I am not doing that for money but if you want to give me some beer money, you can always paypal me [paypal.me/didierbaquier](https://paypal.me/didierbaquier). I always appreciate it. 🍻

**Comment by macsharp** [comment]
@dbaq, Thank you so much for your quick work! I have installed 0.0.7 but I'm still experiencing the same issue... However, I do want to clarify that I thought about the successive calling of the setKey, setName and pick may run into issues, so I called setKey and setName long before the pick (at app init time). I also tried calling these methods right before the .pickMultiple() method, but exhibited the same issue as below. 

Here's my codes, step-by-step action and symptoms of the issue:

Codes:
`filepicker.pickMultiple({
	        multiple: true,
	        mimeTypes: ['image/*', 'application/pdf'],
	        services : [ 'CAMERA', 'GALLERY', 'GOOGLE_DRIVE', 'DROPBOX', 'BOX', 'SKYDRIVE'],
	        maxFiles: 20,
	        maxSize: (10*1024*1024)
	    }, function(res) {
	    	// success
	    	console.log("filePicker return successfully.");
	        console.log(res);
	    }, function(e) {
	    	// error
	    	console.log("filePicker returned an error.");
	       console.error(e);
	    });`

Steps:
1) trigger the call above, the Filestack screen shows up with the correct clout sources.
2) To avoid complicating the issue with iCloud Photostream cacheing, I choose "Camera" and take a photo.
3) Choose "Use Photo", then an upload progress bar shows up, takes ~20 seconds to complete the upload.
4) The progress bar overlay is completed, fades away, and now I'm back to the Filestack view with no action button to confirm my photo selection. See attachment as the screenshot at this moment.

![img_2499](https://user-images.githubusercontent.com/5316195/30646547-65531640-9de7-11e7-80a9-f048677f1f7a.PNG)

So, it appears that I'm still having the same issues... any idea? During this entire process, this isn't much logging from Xcode at all.

Any insight would be greatly appreciated!

**Comment by macsharp** [comment]
@dbaq Strangely, I opened a new FileStack account and the plugin started to work! I wonder if the old age of my previous account (using a grandfather plan) was causing the issue. I'll play with it some more and see how far I can go.

Let me pick your brain on another issue though:
As you know, iOS photos stores most files in iCloud, and these files are synced to local device on-demand (e.g. when you pick a file, the system would start loading the file from iCloud to current device first, then the file object becomes available and the file picker would proceed normally). But with the current FileStack plugin, it doesn't wait for the iCloud data sync and returns an error immediately in Xcode. Here's the log for this issue:
`[Generic] Failed to load image data for asset <PHAsset: 0x10d5267a0> BFBAF3C3-6088-4893-AC7B-F899CBDA3F6A/L0/001 mediaType=1/0, sourceType=1, (640x1136), creationDate=2014-09-06 00:12:21 +0000, location=0, hidden=0, favorite=0  with format 9999
Warning: Attempt to dismiss from view controller <FSPickerController: 0x10480d400> while a presentation or dismiss is in progress!`

Have you run into this issue on your end, and is there a known solution for this problem? Thank you!

**Comment by dbaq** [comment]
hey @macsharp,

> I opened a new FileStack account and the plugin started to work! I wonder if the old age of my previous account (using a grandfather plan) was causing the issue.

Weird. I am also using a old filepicker account (at least 3 years old)

>Let me pick your brain on another issue though:
As you know, iOS photos stores most files in iCloud, and these files are synced to local device on-demand (e.g. when you pick a file, the system would start loading the file from iCloud to current device first, then the file object becomes available and the file picker would proceed normally). But with the current FileStack plugin, it doesn't wait for the iCloud data sync and returns an error immediately in Xcode.

Let's open a new issue for this one. I need to finish the update to the latest version of filestack. Maybe they fixed that issue. (but it definitely seems like an issue in their framework, not in this wrapper).

Also thanks for your donation, I really appreciate it. Last night I was only testing on a simulator. I am going to test on a real iphone right now to make sure the issue is correctly solved.

**Comment by dbaq** [comment]
@macsharp, I tested on an iphone 6 with iOS 11 on it. Everything went well. `pick` and `pickMultiple` are working perfectly with `CAMERA` and `GALLERY` as well.

I uploaded my sample app to a repository, you should check it out: https://github.com/dbaq/cordova-plugin-filepicker-example/tree/master

As far as I can tell, the issue is resolved. I will work soon on the library update to have the latest version.

**Comment by macsharp** [comment]
@dbaq, Just wanted to update you that the FSPicker is still working as expected as long as the photo file is on-device (not synced to the iCloud photo library). For those images that are in the cloud and not on-device, FSPicker will throw an error quietly and unable to perform the upload action. Ideally it should request the file from iCloud photo library, wait for it to cache locally, then complete the upload action. I've reached out to FileStack and see if that is supported at all.

If you've figured out a way to work around this issue, please kindly let me know. Thank you!

**Comment by dbaq** [comment]
I doubt it is handled by filestack, I haven't seen anything in their library. You should open an issue on their repository.
