### ISSUE TITLE
API Key is missing

### ISSUE THREAD

**Issue by sydtpt** [dbaq/cordova-plugin-filepickerio#20]
Hello guys,

Could someone help me?

I'm trying to implement this plugin and I'm getting an error:

"API Key is missing".

Here is my code:
`filepicker.setKey('com.totvs.services.mobile.legaltask');
filepicker.setName('legaltask')
filepicker.pick(
    {
            services: ["GALLERY", "CAMERA", "FACEBOOK", "CLOUDDRIVE", "DROPBOX", "BOX", "GMAIL", "INSTAGRAM", "FLICKR", "PICASA", "GITHUB", "GOOGLE_DRIVE", "EVERNOTE", "SKYDRIVE"],
    },
    {
            multiple:false,
            location: 'gcs'
    }, (res) => {
            console.log(res);
    }, (e) => {
            console.error('file picker error: ');
            console.error(e);
});`

Is that correct, do I need to pass my package name in the setKey('') funcution? (for Both , IOs and Android).

And about the setName('')?

The return is falling on the success callback.

**Comment by spixy** [comment]
I have the same problem. Documentation for this plugin is not complete :/
Have you found solution?

**Comment by spixy** [comment]
solution:
login on https://www.filestack.com and you will get API key, if you still want to use this plugin
