### ISSUE TITLE
Andriod issues: No API Key, Network Error, and Image or Video but not both

### ISSUE THREAD

**Issue by adamjpeterson** [dbaq/cordova-plugin-filepickerio#22]
This seems to work great for iOS but not for Android. When on Android, the first time it loads I always get a No API Key error. The second time the button correctly loads the Camera or Gallery icons, but when selecting a video I get a Network Error error. Note, this all works great on iOS so I'm not sure of the bug. Also note, on Android I can only get video or images to be allowed, never both. I have to set video/* or image/* as the mimetypes. My code is quite simple:

    window.filepicker.setKey('XXXXX');
    window.filepicker.setName('Acme');
    window.filepicker.pick({
        services : [ 'CAMERA', 'GALLERY'],
        mimeTypes: ['video/*']
    }, function(res) {
        //do something
    }, function(e) {
        //do something
    });

**Comment by adamjpeterson** [comment]
Note that all of the above worked when I upgraded cordova and android to all the most recent versions.

**Comment by dbaq** [comment]
Thanks for the feedback @adamjpeterson.
