### ISSUE TITLE
Require Released Version Containing plugin.xml Fixes

### ISSUE THREAD

**Issue by Jitsusama** [dbaq/cordova-plugin-filepickerio#25]
Hello!

First of all, thanks for the project!

Second of all, I would really like to have a version of this project pushed to NPM which includes the last 2 PRs concerning updates to plugin.xml. I'm getting bit by the embeddable frameworks not being auto-set, as I share a Cordova project with other team-mates, and we really want to be able to auto-generate Xcode projects that will work out of the box.

Would you mind creating a 0.0.9 version or some such and post it up to NPM? Thanks!

**Comment by dbaq** [comment]
Hi @Jitsusama,

I just published a new version on npm:

```
npm notice name:          cordova-plugin-filepickerio
npm notice version:       0.0.9
npm notice package size:  1.6 MB
npm notice unpacked size: 6.0 MB
npm notice shasum:        36856efbbef5663e412ae6010d6ea257cf6df4b1
npm notice integrity:     sha512-FA/p8samuVAek[...]U3bIS6dmDtC0Q==
npm notice total files:   121
npm notice
+ cordova-plugin-filepickerio@0.0.9
```

Enjoy!

**Comment by Jitsusama** [comment]
Thanks so much!
