### ISSUE TITLE
Did not work. Any example ?

### ISSUE THREAD

**Issue by e-vural** [dbaq/cordova-plugin-filepickerio#5]
İ installed and try try but plugin did not work.  Always work error function.  Please help me

**Comment by dbaq** [comment]
Hey @emrevural20, we are using this plugin in production, it is working as intended. Can you please share some code/stacktrace so I can help you figure this out.

**Comment by MHabashy10** [comment]
Hi,

Thank you so much for this plugin, filestack works like charm in browser so we would like to integrate it in our ionic app.

For starters we wanted to open the picker to choose a file however the modal didn't shows up entirely and the success callback is called directly with undefined.

Our environment: 
ionic V1
cordova V7
inappbrowser plugin already installed 
<allow-navigation href="*" /> is already in our config.xml 

Code 

```
function showPicker() {
           
             window.filepicker.setKey('APP KEY'); // replaced the APP KEY with mine 
            
            window.filepicker.pick({
                multiple: false,
                mimeTypes: ['image/*'],
                services: ['GALLERY']
            }, function (res) {
                console.log(JSON.stringify(res))
            }, function (e) {
                console.error(e);
            });
}
```

any suggestions? 
Thanks in advance.

Regards,
Mohamed

**Comment by dbaq** [comment]
hello @Mohamed-Habshey,

do you see a stacktrace in xcode or logcat?

**Comment by MHabashy10** [comment]
hi @dbaq 
no traces in logcat only the console log 

``` 
D/SystemWebChromeClient(29127): http://192.168.2.22:8100/#/tab/feed: Line 220 : undefined
I/chromium(29127): [INFO:CONSOLE(220)] "undefined", source: http://192.168.2.22:8100/#/tab/feed (220)
```

**Comment by dbaq** [comment]
The `undefined` error means (most of the time) that the plugin is not installed properly. Can you double check that the plugin is correctly installed please?

**Comment by MHabashy10** [comment]
Oh i think maybe i wasn't clear about the logcat 

line 220 corresponds to 
```  console.log(JSON.stringify(res))```
in the above code snap which is the success callback, so i think the plugin is installed correctly, however i checked again the installation everything looks good. 

i doubt it would be installation problem, it could be related to ionic maybe?

Best

**Comment by dbaq** [comment]
Can you try again with the latest version of master please?

**Comment by e-vural** [comment]
I tryed lastest version. Success function is work but response only true. Picker dosen't open. 

this is picker function

`

function openFilePickerIo(e) {

    window.filepicker.setKey('com.vural.filepickerio');
    window.filepicker.setName('HelloCordova');
    window.filepicker.pickMultiple({
        multiple: true,
        mimeTypes: ['image/*', 'application/pdf'],
        services : [ 'CAMERA', 'GALLERY'],
        maxFiles: 20,
        maxSize: (10*1024*1024)
    }, function(res) {
        console.log(res);
    }, function(e) {
        console.error(e);
    });
};
 `

This is success function console.log
`I/chromium(24425): [INFO:CONSOLE(81)] "true", source: file:///android_asset/www/js/index.js (81)
`

**Comment by dbaq** [comment]
do you set the correct filepicker key? is it on android or ios? can you check logcat or the xcode logs please?

**Comment by e-vural** [comment]
What is the correct filepicker key?  Where is it ? My codes like above. ( before comment ). System is android.

**Comment by dbaq** [comment]
the filepicker/filestack key is accessible in the filestack dashboard
