### ISSUE TITLE
dyld: Library not loaded: @rpath/FSPicker.framework/FSPicker

### ISSUE THREAD

**Issue by infiniteloopltd** [dbaq/cordova-plugin-filepickerio#8]
After adding this filepicker plugin to my cordova project, I got this error at build time in Xcode:

dyld: Library not loaded: @rpath/FSPicker.framework/FSPicker

  Referenced from: /Users/fiachreid/Library/Developer/CoreSimulator/....

  Reason: image not found

Has anyone seen this error?

**Comment by dbaq** [comment]
> dyld: Library not loaded: @rpath/FSPicker.framework/FSPicker

it looks like the library FSPicker is not imported correctly in your xcode project.

Make sure all these frameworks are included properly: https://github.com/dbaq/cordova-plugin-filepickerio/blob/master/plugin.xml#L44-L53

**Comment by infiniteloopltd** [comment]
Ok, found the solution;

In the embedded binaries section of the target (General tab), you have to add FSPicker.framework, AFNetworking.framework, and FileStack.framework.

I also discovered, if you try to submit an app with these frameworks, Apple complains that there are unsupported architectures; I found a solution to this also using this build script; http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

Thanks!

**Comment by dbaq** [comment]
> I also discovered, if you try to submit an app with these frameworks, Apple complains that there are unsupported architectures; I found a solution to this also using this build script; http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

very true, I used the same blog post when I pushed the app to the store. I should add it to the readme file.

I am closing the issue since you solved it. Have a good weekend.
